version: '3.8'

services:
  app:
    build:
      context: ./docker  # O diretório de build é o diretório onde o Dockerfile está localizado
      dockerfile: Dockerfile  # O nome do Dockerfile dentro da pasta 'docker'
    ports:
      - "8501:8501"
    volumes:
      - ./docker:/app  # Monta o diretório 'docker' para o diretório '/app' no contêiner
    depends_on:
      - db
    networks:
      - app_net

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_net

volumes:
  pgdata: 

networks:
  app_net:
    driver: bridge
